### ISSUE TITLE
Clang-tidy flakes in CI

### ISSUE THREAD

**Issue by oschaaf** [envoyproxy/nighthawk#161]
The following failure seems to occur every now and then in clang-tidy runs:

```
Restarted CI because of a `clang-tidy` flake, second time I noticed this.
Failure:
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/build/tmp/_bazel_bazel/f85b6fb5740e6e8c7efea142eec4b6e8/server/jvm.out')

Traceback (most recent call last):
  File "tools/gen_compilation_database.py", line 83, in <module>
    generateCompilationDatabase(args)
  File "tools/gen_compilation_database.py", line 11, in generateCompilationDatabase
    subprocess.check_call(["bazel", "build"] + args.bazel_targets)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
```

**Comment by oschaaf** [comment]
Re-opening, because clang-tidy still flakes, so apparently I didn't address that part appropriately.

**Comment by oschaaf** [comment]
I haven’t seen this CI test flake in a while. closing
